# base image
FROM golang:1.26.1-alpine3.23
# set up work directory
WORKDIR /opt/app
# copy app files
COPY . .
# install dependencies
RUN go mod download && \
    go mod verify
# build app
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/app .
# define run command
ENTRYPOINT [ "app" ]
