# https://docs.docker.com/compose/compose-file/
services:
  server-a:
    image: ghcr.io/mmorejon/erase-una-vez-2:v0.5.0
    entrypoint: server
    platform: linux/amd64
    environment:
      CHARACTER: "server a"
  server-b:
    image: ghcr.io/mmorejon/erase-una-vez-2:v0.5.0
    entrypoint: server
    platform: linux/amd64
    environment:
      CHARACTER: "server b"
  client:
    image: ghcr.io/mmorejon/erase-una-vez-2:v0.5.0
    entrypoint: client
    platform: linux/amd64
    environment:
      ENDPOINT: "http://server-a:8000/echo"
